---
experiment:
  name: tiger_detection_deep_every_layer_add_one_diff_schedulers_exp_1 # change
  folder: /Users/grego/Downloads/FYP
phase: train
task: detect

train:
  ann_path: /Users/grego/Downloads/FYP/data/train_output.json
  img_path: /Users/grego/Downloads/FYP/data/train_images
  img_size: 224
  transform: strong
val:
  ann_path: /Users/grego/Downloads/FYP/data/val_output.json
  img_path: /Users/grego/Downloads/FYP/data/val_images
  img_size: 224
  transform: weak

model:
  load_weights: False
  weights_path: /home/haribo/okupyn_exp/binary_fpn_lowaug/best.h5
  pretrain_weights: /Users/grego/Downloads/FYP/mobilenet_v2.pth.tar
  num_classes: 2
  img_size: 224
  feature_maps: 6
  name: retina_net
  backbone: mobilenet_v2_deep_every_layer_add_one # change
  encoder_depth: 50
  pretrained: True
  visual_thr: 0.25

  loss:
    name: multibox_loss
    localization_loss: l1_smooth_loss
    confidence_loss: cross_entropy_loss

optimizer:
  name: adam
  lr: 0.0001 # Initial 0.001 # changeable
  appended_lr: 0.001 # changeable

scheduler:
  name: plateau
  mode: max
  patience: 5
  factor: 0.5
  min_lr: 0.000001

batch_size: 16
num_epochs: 50
early_stopping: 15
